ietf-wg-masque/draft-ietf-masque-h3-datagram

draft-h3-datagram.md

Editorial nits

---

draft-schinazi-masque-h3-datagram.md

Clarify 0-RTT value cannot exceed 1

---

draft-schinazi-masque-h3-datagram.md

Allow retiring flow identifiers

---

draft-ietf-masque-h3-datagram.md

Remove reuse

---

draft-ietf-masque-h3-datagram.md

Remove ECN example

---

draft-ietf-masque-h3-datagram.md

Add text about sticking out

---

draft-ietf-masque-h3-datagram.md

This PR aims to take the design discussions we had at the last
interim, and propose a potential solution. This PR should in theory
contain enough information to allow folks to implement this new
design. That will allow us to perform interop testing and confirm
whether the design is sound.
[An HTML version of the draft with these changes is available here.](https://ietf-wg-masque.github.io/draft-ietf-masque-h3-datagram/two_layer_capsule/draft-ietf-masque-h3-datagram.html)
Closes #41, closes #42, closes #43, closes #44.

Two layer design with CAPSULE

---

draft-ietf-masque-h3-datagram.md

This change allows clients to disable contexts for a given stream.
This uses a new REGISTER_DATAGRAM_NO_CONTEXT capsule for negotiation.
The important property here is that it requires capsule support even
when contexts are not required. This is critical to the health of the
ecosystem as it will ensure that intermediaries that support datagrams
but not capsules cannot be deployed, as that would prevent future
extensibility.
Closes #45.

Make contexts optional

---

draft-ietf-masque-h3-datagram.md

Allow keeping receive around for a short time

---

draft-ietf-masque-h3-datagram.md

This will help interop efforts before publication.

Specify how to support multiple drafts

---

draft-ietf-masque-h3-datagram.md

Credit to @bemasc for the proposal on the [mailing list](https://mailarchive.ietf.org/arch/msg/masque/7KJiS6bznHSlCqz1q8HTXoAk0to/).
Closes #65.

Do not convert datagrams to capsules

---

draft-ietf-masque-h3-datagram.md

intermediaries do not have to buffer DATAGRAMs

---

draft-ietf-masque-h3-datagram.md

Editorial: fix tables

---

draft-ietf-masque-h3-datagram.md

Use of contexts is not negotiated, it is decided unilaterally by the client

---

draft-ietf-masque-h3-datagram.md

fixes #92 
err'ing on the side of succinct

document the document structure

---

draft-ietf-masque-h3-datagram.md

fix CONNECT-UDP examples

---

draft-ietf-masque-h3-datagram.md

This PR attempts to meet the majority of requirements from the design team's discussion on 2021-11-15, while removing all other features.
Note that this PR is against the design team consensus branch, not main.
[Rendered view of this PR](https://ietf-wg-masque.github.io/draft-ietf-masque-h3-datagram/design_team_output/draft-ietf-masque-h3-datagram.html).
[Rendered diff with the design team consensus branch](https://www.ietf.org/rfcdiff?url1=https://ietf-wg-masque.github.io/draft-ietf-masque-h3-datagram/draft-ietf-masque-h3-datagram.txt&url2=https://ietf-wg-masque.github.io/draft-ietf-masque-h3-datagram/design_team_output/draft-ietf-masque-h3-datagram.txt).

First PR for 2021 Design Team

---

draft-ietf-masque-h3-datagram.md

Clarify meaning of understanding capsule request semantics

---

draft-ietf-masque-h3-datagram.md

This PR represents the consensus of the 2021 MASQUE Design Team.
[Rendered view of this PR](https://ietf-wg-masque.github.io/draft-ietf-masque-h3-datagram/2021_design_team_consensus/draft-ietf-masque-h3-datagram.html).
[Rendered diff with the editor's copy](https://www.ietf.org/rfcdiff?url1=https://ietf-wg-masque.github.io/draft-ietf-masque-h3-datagram/draft-ietf-masque-h3-datagram.txt&url2=https://ietf-wg-masque.github.io/draft-ietf-masque-h3-datagram/2021_design_team_consensus/draft-ietf-masque-h3-datagram.txt).
cc @afrind @LPardue @MikeBishop @martinthomson @vasilvv @ekr @achernya @bemasc @tfpauly @ihlar
Fixes #84
Fixes #107
Fixes #117 
Fixes #118
Fixes #125
Fixes #126
Fixes #127

HTTP Datagrams: 2021 Design Team Consensus

---

draft-ietf-masque-h3-datagram.md

Revisit sticking out text now that document has evolved

---

draft-ietf-masque-h3-datagram.md

Cleanup IANA details for h3 setting

---

draft-ietf-masque-h3-datagram.md

Fixes #128.
Fixes #129.
Fixes #130.
Fixes #131.
Fixes #137.

Tighten requirements on the capsule protocol

---

draft-ietf-masque-h3-datagram.md

Provide guidance for handling overly large datagram capsules

---

draft-ietf-masque-h3-datagram.md

Disallow capsule pipelining

---

draft-ietf-masque-h3-datagram.md

don't allow quarter stream ID beyond limits

---

draft-ietf-masque-h3-datagram.md

This just stuck out as something worth explicitly mentioning in the abstract (and therefore the intro).

mention Capsule Protocol early

---

draft-ietf-masque-h3-datagram.md

- make HTTP version refs smarter
- ref something for upgrade token
- ref structured fields smarter

Reference improvements

---

draft-ietf-masque-h3-datagram.md

Fixes #153
Fixes #155
Fixes #156

Mnot refactor

---

draft-ietf-masque-h3-datagram.md

Clarify guidance of Capsule-Protocol header

---

draft-ietf-masque-h3-datagram.md

Remove notion of datagram-related state

---

draft-ietf-masque-h3-datagram.md

supports -> willing to receive

---

draft-ietf-masque-h3-datagram.md

Be explicit about concepts in the abstract

---

draft-ietf-masque-h3-datagram.md

... and indirectly associated with streams
Closes #175

Datagrams are directly associated with requests

---

draft-ietf-masque-h3-datagram.md

Clarify clean stream termination

---

draft-ietf-masque-h3-datagram.md

Closes #174
Using a slight variation of David's proposed text on the issue.

Be clearer about the H3 setting in intro

---

draft-ietf-masque-h3-datagram.md

Clarify that WebSocket is an example

---

draft-ietf-masque-h3-datagram.md

Clarify no blind reencoding

---

draft-ietf-masque-h3-datagram.md

Be more honest about the mapping between app and transport

---

draft-ietf-masque-h3-datagram.md

Closes #181
This looks big but it consists of some minor operations
* H3_DATAGRAM -> SETTINGS_H3_DATAGRAM
* SETTINGS parameter -> setting
* Tweak the security considerations so it is explicit and grammar ain't borke

SETTINGS parameter -> setting

---

draft-ietf-masque-h3-datagram.md

Update references to use the right display form

---

draft-ietf-masque-h3-datagram.md

Clarify that there is no content with capsules

---

draft-ietf-masque-h3-datagram.md

Clarify that the optionality of capsules applies to extensions

---

draft-ietf-masque-h3-datagram.md

Switch to QUIC IANA policy

---

draft-ietf-masque-h3-datagram.md

length is in bytes

---

draft-ietf-masque-h3-datagram.md

Written in response to [Roman's COMMENT](https://mailarchive.ietf.org/arch/msg/masque/16NJtUKTP6FMK-AuGjhbQfujS9k/)

New upgrade tokens need security analysis
