draft-schinazi-quic-h3-datagram.md

The comparison to UDP sockets is not as good as a comparison to streams.
UDP sockets are sometimes spun up in the fashion described, but they are
also often a fixed thing, such as the socket that a DNS server listens
on.  That evokes the wrong model in which the caller chooses and there
is some possibility of persistence.

Simplify analogy

---

draft-schinazi-masque-h3-datagram.md

This PR switches the header to a list on MT's suggestion to make the semantics clearer.
Closes #9
Closes #11
Closes #12
Closes #13

Make Datagram-Flow-Id a list

---

draft-schinazi-masque-h3-datagram.md

frames too short for flow ID cause H3 errors

---

draft-ietf-masque-h3-datagram.md

This somewhat of an experiment. While trying to address #27 I got distracted by the document's use of the "flow identifier" term.
The document likes to compare "flow identifiers" with QUIC streams, which is fine. But QUIC makes the distinction between streams and stream IDs; the ID is a property of the stream but it isn't the only one, and sometimes it helps to talk about the stream in other contexts.
This change tries to channel a similar editorial style. It replaces:
* "flow identifiers" with "flows" when talking about a logical entitiy
* "flow identifiers" with "flow IDs" when talking about the wire format, encoding, examples etc.
This could be a change too far but I figured it would be a good discussion starter.

Split flow identifier term to flows and IDs

---

draft-ietf-masque-h3-datagram.md

Remove guidance about packing DATAGRAM frames in packets

---

draft-ietf-masque-h3-datagram.md

This prevents some flavors of DoS attacks and provides clearer assumptions to endpoints.

Add some rules on ordering of register capsules

---

draft-ietf-masque-h3-datagram.md

Minor editorial clarification.
Closes #40.

Clarify datagram lifetime with stream

---

draft-ietf-masque-h3-datagram.md

Punt prioritization to extensions like QUIC and HTTP/3 did.
Closes #46.

Make prioritization undefined

---

draft-ietf-masque-h3-datagram.md

Contexts are end-to-end, and intermediaries MUST NOT parse them.
Closes #54.

Clarify intermediary parsing rules

---

draft-ietf-masque-h3-datagram.md

This PR adds a new concept of context close codes which
will allow applications that use contexts to indicate
the reason for closing a context.
This PR also makes the extensibility mechanism binary as
that is easier to implement.
Closes #53.

Add context close codes and make extensibility binary

---

draft-ietf-masque-h3-datagram.md

@afrind points out that in order to correctly forward DATAGRAMs between transports where the QUIC DATAGRAM frame isn't always available, intermediaries need the ability to parse some capsules.

Clarify Opaque Capsules

---

draft-ietf-masque-h3-datagram.md

This makes the requirement global to clients, servers, and
intermediaries.
closes #73

make CAPSULE frame ordering wrt HEADERS a global requirement

---

draft-ietf-masque-h3-datagram.md

As per h3 rules, it's fine to send capsules without a setting. The setting is about the semantics of datagrams. Also remove the requirement to send the datagram transport parameter because we now have capsules.
Closes #85

Clarify that the H3_DATAGRAM setting applies only to datagrams

---

draft-ietf-masque-h3-datagram.md

After spending some time on CONNECT-IP, I realized that the current design won't work well. The primary motivation for including contexts and formatting in this document (as opposed to in the individual drafts) is that it allows to build a layer that can handle extensions without round trip negotiations: in particular it means clients can start using an extension format immediately without waiting for the HTTP response. For that to work, the server needs to drop unknown formats, so we need a single format enum as opposed to a list of them - that way the entire context is ignored instead of accepting the context but ignoring the extension that might have changed the encoding.
[Rendered view of this PR here](https://ietf-wg-masque.github.io/draft-ietf-masque-h3-datagram/rework_extensibility/ …

Rework how datagram format extensibility works

---

draft-ietf-masque-h3-datagram.md

The thing that sucks here is that the diagram won't auto expand `{{iana-types}}`, so we can't easily ref the section. Manually referring to the section is a maintenance pain. So instead just state the actual type in the text an the diagram. I have a feeling you were linking to the section to avoid the maintenance hassle of updating type codes in multiple place. But I'm quite happy to take that burden because I find it more pleasant to read this way.
fixes #94

expand capsule diagrams to include all fields

---

draft-ietf-masque-h3-datagram.md

[WebTransport](https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3) uses HTTP Datagrams but doesn't currently have a need for datagram contexts. Because of this, some members of the WebTransport community prefer to not have to implement datagram contexts. This PR changes how datagram contexts are negotiated to make them optional to implement. One important design goal of this change was to allow optimistic use of contexts: in other words, the client shouldn't have to wait a round trip to find out whether contexts are supported before being able to optimistically use them.
Before this PR, contexts were mandatory to implement and the client would decide whether to use them by sending either REGISTER_DATAGRAM_CONTEXT or REGISTER_DATAGRAM_NO_CONTEXT.
With this PR, endpoints use a …

Make datagram contexts optional to implement

---

draft-ietf-masque-h3-datagram.md

Borrowing text from H3.  Also I don't think there is a 'FRAME_ENCODING_ERROR' defined anywhere.

Treat malformed capsules as stream errors

---

draft-ietf-masque-h3-datagram.md

When reviewing the latest editors copy, the document structure leaps out at a bit odd by jumping from section 3 to section 5. That indicates to me these concepts are linked and also independent of the capsule protocol.
So here I propose a minor restructure by moving the H3_DATAGRAM setting stuff to be a subsection of the HTTP/3 datagram format. This makes all the top-layer sections loosely coupled, which is nicer in my opinion.

move the H3 setting definition alongside it's related format

---

draft-ietf-masque-h3-datagram.md

It's shorter and apparently the tagging is what is now required later on in the RFC process anyway.

use bcp14-tagged macro

---

draft-ietf-masque-h3-datagram.md

The HTTP WG is working on a style guide, see https://github.com/httpwg/admin/blob/main/style-guide.md
In line with the style, the reference to structured fields is updated in #147 because it's less contentious. What remains here is probably more so.
First, move the consideration for intermediaries to the bottom of the section. It doesn't seem a leading item to me. 
Then we start the section with a  focus on defining the field itself. The ABNF is probably the bit we'll disagree with. It seems in trying to be specific on the Item type, you've written out the the subcomponents of the ABNF. This is something that is being discussed in the HTTP WG list. Personally I don't like being overly specific in the ABNF because it could be misconstrued as something that is SF-like but not really SF. As …

Changes to Capsule-Protocol header section

---

draft-ietf-masque-h3-datagram.md

Nit from AD review:
The original sentence is ambiguously worded, and could be interpreted as saying that there could not be normal HTTP requests prior to the capsule protocol.

reword sentence

---

draft-ietf-masque-h3-datagram.md

This adds a few statements through the text that explains that data
streams are subject to any flow control provided by layers lower down.
Wih that in mind, the potential for problem deadlocks should be clearer
when we state it.
Fixes #199

Data streams are subject to underlying layer's flow control

---

draft-ietf-masque-h3-datagram.md

Explicitly replicates parts of H2 and H3 CONNECT stream definition to
make it clear what frame types are/are not allowed on a stream.
Mostly anything else can't happen but if it does, approach error
handling _as if it were like_ a malformed message (I.e whether to
terminate the stream or whatever).
Fixes #200

Be clearer about message error vs. stream errors
